# Generated by Django 3.1.7 on 2021-03-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210306_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
