# Generated by Django 3.1.7 on 2021-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210313_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='logo',
            field=models.ImageField(blank=True, max_length=240, null=True, upload_to='media'),
        ),
    ]
